name: monorepo-gate
on:
  pull_request:
    branches: [ master ]
jobs:
  quality-gate:
    uses: ./.github/workflows/template-dotnet-ci.yml
    with:
      service_name: 'Monorepo'
      project_path: '.' 
      bypass_checks: true
    secrets: inherit
